# Generated by Django 3.2.6 on 2022-04-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=120)),
                ('visit_date', models.DateTimeField()),
                ('reason', models.CharField(max_length=500)),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
    ]
