# Generated by Django 3.2.6 on 2022-04-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorvisit',
            name='doctor',
            field=models.CharField(max_length=120, verbose_name='Doctor Name'),
        ),
        migrations.AlterField(
            model_name='doctorvisit',
            name='notes',
            field=models.CharField(max_length=500, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='doctorvisit',
            name='reason',
            field=models.CharField(max_length=500, verbose_name='Reason of Viit'),
        ),
        migrations.AlterField(
            model_name='doctorvisit',
            name='visit_date',
            field=models.DateTimeField(verbose_name='Visit Date'),
        ),
    ]
