# Generated by Django 4.0.3 on 2022-04-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_doctorvisit_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorvisit',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='doctorvisit',
            name='reason',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Reason of Visit'),
        ),
        migrations.AlterField(
            model_name='doctorvisit',
            name='visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Visit Date'),
        ),
    ]
