# Generated by Django 3.2.6 on 2022-04-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_doctorvisit_notes_alter_doctorvisit_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=120, verbose_name='Doctor Name')),
                ('noofpeople', models.CharField(blank=True, max_length=500, null=True, verbose_name='Reason of Visit')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Visit Date')),
                ('time', models.CharField(blank=True, max_length=500, null=True, verbose_name='Notes')),
                ('reason', models.IntegerField(blank=True, max_length=500, null=True, verbose_name='id')),
            ],
        ),
        migrations.AddField(
            model_name='doctorvisit',
            name='user',
            field=models.IntegerField(blank=True, max_length=500, null=True, verbose_name='id'),
        ),
    ]
