# Generated by Django 3.2.6 on 2022-04-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220410_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=120, verbose_name='Medicine')),
                ('Nooftimesaday', models.CharField(blank=True, max_length=500, null=True, verbose_name='No of times a day')),
                ('fromdate', models.DateField(blank=True, null=True, verbose_name='from')),
                ('to', models.DateField(blank=True, null=True, verbose_name='to')),
                ('reason', models.CharField(blank=True, max_length=500, null=True, verbose_name='reason')),
            ],
        ),
        migrations.AlterField(
            model_name='familyvisit',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='familyvisit',
            name='location',
            field=models.CharField(max_length=120, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='familyvisit',
            name='noofpeople',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='No of people'),
        ),
        migrations.AlterField(
            model_name='familyvisit',
            name='reason',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='familyvisit',
            name='time',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='time'),
        ),
    ]
