# Generated by Django 3.2.6 on 2022-04-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220410_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=120, verbose_name='Destination')),
                ('duration', models.IntegerField(blank=True, max_length=500, null=True, verbose_name='Duration')),
                ('fromdes', models.DateField(blank=True, null=True, verbose_name='From')),
                ('to', models.DateField(blank=True, null=True, verbose_name='To')),
            ],
        ),
    ]
