# Generated by Django 3.2.6 on 2022-04-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_trips'),
    ]

    operations = [
        migrations.CreateModel(
            name='Takeouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=120, verbose_name='Restaurant / Cafe')),
                ('type', models.CharField(blank=True, max_length=500, null=True, verbose_name='Type')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Time')),
            ],
        ),
    ]
