# Generated by Django 3.2.6 on 2022-04-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_takeouts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine', models.CharField(max_length=120, verbose_name='Vaccine')),
                ('dose1', models.DateField(blank=True, null=True, verbose_name='Dose 1')),
                ('dose2', models.DateField(blank=True, null=True, verbose_name='Dose 2')),
                ('booster', models.DateField(blank=True, null=True, verbose_name='Booster')),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='Notes')),
                ('user', models.IntegerField(blank=True, max_length=500, null=True, verbose_name='id')),
            ],
        ),
        migrations.AddField(
            model_name='familyvisit',
            name='user',
            field=models.IntegerField(blank=True, max_length=500, null=True, verbose_name='id'),
        ),
        migrations.AddField(
            model_name='medicinelist',
            name='user',
            field=models.IntegerField(blank=True, max_length=500, null=True, verbose_name='id'),
        ),
        migrations.AddField(
            model_name='takeouts',
            name='user',
            field=models.IntegerField(blank=True, max_length=500, null=True, verbose_name='id'),
        ),
        migrations.AddField(
            model_name='trips',
            name='user',
            field=models.IntegerField(blank=True, max_length=500, null=True, verbose_name='id'),
        ),
    ]
