# Generated by Django 3.2.6 on 2022-04-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220410_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(max_length=120, verbose_name='Temperature')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Time')),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='Notes')),
                ('user', models.IntegerField(blank=True, max_length=500, null=True, verbose_name='id')),
            ],
        ),
    ]
